### ISSUE TITLE
grid on roster

### ISSUE THREAD

**Issue by toozej** [DanAlbert/whdsched#21]
Roster should show some borders, and a line/box around the header of the columns to improve readability

**Comment by toozej** [comment]
also of note, very subtle coloured rows appear on Today's schedule in Firefox, but they are close enough to invisible on Chrom(e/ium). I like the idea of having them coloured, might I suggest a light blue? Should go with whatever colour theme we end up choosing....

**Comment by DanAlbert** [comment]
Grid now exists on the roster. As far as the faint colors, that's actually an issue with monitor quality rather than your browser. I've been testing the website on my old monitor the whole time. When I finally moved it to a monitor with a decent backlight, the rows were incredibly faint. I'll have to do some playing. Thanks for the warning.

**Comment by toozej** [comment]
I can't see the grid, I guess it might just be running on the latest revision code that hasn't been pushed to the "live" dev site yet...

**Comment by toozej** [comment]
new layout works, no visible grid lines but its much more readable now

**Comment by DanAlbert** [comment]
Alright, darkened them.
