### ISSUE TITLE
unable to logout

### ISSUE THREAD

**Issue by toozej** [DanAlbert/whdsched#24]
Have been unable to logout multiple times, from all possible pages. received message "Unable to log out" on URL  https://secure.engr.oregonstate.edu/helpdesk-staff/dev/whdsched/public/index/logout. Return to main page button works as it should, am still logged in after returning to main page

**Comment by toozej** [comment]
due to engr authentication on the helpdesk-staff path, whenever you close the whdsched window and go to the whdsched main page you are prompted to log back in. so the above issue might be a mute point.

**Comment by DanAlbert** [comment]
It's due to the fact that the actual authentication is being done by Apache rather than by us. I can clear the site log in, but Apache (or perhaps the browser) keeps the session open. I'm going to do some digging to see if I can tell Apache to force another log in. We had it on the ticket system, so I just need to figure out how.

**Comment by DanAlbert** [comment]
:(
